# Generated by Django 4.0.4 on 2022-06-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(max_length=128)),
                ('tag_price', models.CharField(max_length=128)),
                ('tag_image_url', models.URLField(max_length=256)),
            ],
            options={
                'db_table': 'shoes',
            },
        ),
    ]
