# Generated by Django 4.0.5 on 2022-06-10 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
            ],
            options={
                'db_table': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Shoe_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(max_length=50)),
                ('tag_price', models.IntegerField()),
                ('tag_image_url', models.URLField(verbose_name='Site_URL')),
            ],
            options={
                'db_table': 'Shoe_tag',
            },
        ),
        migrations.CreateModel(
            name='Post_Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_img', models.ImageField(upload_to='media/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
            options={
                'db_table': 'Post_Img',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='shoe_tags',
            field=models.ManyToManyField(related_name='shoe_taggie', to='post.shoe_tag'),
        ),
    ]
