# Generated by Django 4.0.4 on 2022-06-12 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoetag',
            name='tag_price',
        ),
    ]
