# Generated by Django 4.0.5 on 2022-06-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe_tag',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='shoe_tags',
            field=models.ManyToManyField(related_name='posts', to='post.shoe_tag'),
        ),
    ]
