# Generated by Django 4.0.5 on 2022-06-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimg',
            name='post_img',
            field=models.URLField(),
        ),
    ]
