# Generated by Django 4.0.5 on 2022-06-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_shoe_tag_posts_post_shoe_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_img',
            old_name='posts',
            new_name='post',
        ),
    ]
