# Generated by Django 4.0.5 on 2022-06-22 03:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='follow',
            field=models.ManyToManyField(null=True, related_name='followee', to=settings.AUTH_USER_MODEL),
        ),
    ]
